services:
  postgres:
    image: postgres:18
    container_name: fleet-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleetpass
      POSTGRES_DB: fleetdb

    ports:
      - "5432:5432"

    volumes:
      - ./data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
