// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/fleet.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_NONE      CommandType = 0
	CommandType_STOP      CommandType = 1
	CommandType_CONTINUE  CommandType = 2
	CommandType_NEW_ROUTE CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "NONE",
		1: "STOP",
		2: "CONTINUE",
		3: "NEW_ROUTE",
	}
	CommandType_value = map[string]int32{
		"NONE":      0,
		"STOP":      1,
		"CONTINUE":  2,
		"NEW_ROUTE": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fleet_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_fleet_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       int32                  `protobuf:"varint,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetTruckId() int32 {
	if x != nil {
		return x.TruckId
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Points        map[int32]*Point       `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetPoints() map[int32]*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       int32                  `protobuf:"varint,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Battery       float64                `protobuf:"fixed64,4,opt,name=battery,proto3" json:"battery,omitempty"`
	State         int32                  `protobuf:"varint,5,opt,name=State,proto3" json:"State,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *Telemetry) GetTruckId() int32 {
	if x != nil {
		return x.TruckId
	}
	return 0
}

func (x *Telemetry) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Telemetry) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Telemetry) GetBattery() float64 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *Telemetry) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Telemetry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=fleet.CommandType" json:"type,omitempty"`
	Route         []int32                `protobuf:"varint,2,rep,packed,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_NONE
}

func (x *Command) GetRoute() []int32 {
	if x != nil {
		return x.Route
	}
	return nil
}

var File_proto_fleet_proto protoreflect.FileDescriptor

const file_proto_fleet_proto_rawDesc = "" +
	"\n" +
	"\x11proto/fleet.proto\x12\x05fleet\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\",\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\x05R\atruckId\"\xb4\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12;\n" +
	"\x06points\x18\x02 \x03(\v2#.fleet.RegisterResponse.PointsEntryR\x06points\x1aG\n" +
	"\vPointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.fleet.PointR\x05value:\x028\x01\"\x90\x01\n" +
	"\tTelemetry\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\x05R\atruckId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\abattery\x18\x04 \x01(\x01R\abattery\x12\x14\n" +
	"\x05State\x18\x05 \x01(\x05R\x05State\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"G\n" +
	"\aCommand\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.fleet.CommandTypeR\x04type\x12\x14\n" +
	"\x05route\x18\x02 \x03(\x05R\x05route*>\n" +
	"\vCommandType\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\f\n" +
	"\bCONTINUE\x10\x02\x12\r\n" +
	"\tNEW_ROUTE\x10\x032\x83\x01\n" +
	"\fFleetService\x12@\n" +
	"\rRegisterTruck\x12\x16.fleet.RegisterRequest\x1a\x17.fleet.RegisterResponse\x121\n" +
	"\rSendTelemetry\x12\x10.fleet.Telemetry\x1a\x0e.fleet.CommandB9Z7github.com/MrBeetMaker/fleet-optimization/proto;fleetpbb\x06proto3"

var (
	file_proto_fleet_proto_rawDescOnce sync.Once
	file_proto_fleet_proto_rawDescData []byte
)

func file_proto_fleet_proto_rawDescGZIP() []byte {
	file_proto_fleet_proto_rawDescOnce.Do(func() {
		file_proto_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)))
	})
	return file_proto_fleet_proto_rawDescData
}

var file_proto_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_fleet_proto_goTypes = []any{
	(CommandType)(0),         // 0: fleet.CommandType
	(*Point)(nil),            // 1: fleet.Point
	(*RegisterRequest)(nil),  // 2: fleet.RegisterRequest
	(*RegisterResponse)(nil), // 3: fleet.RegisterResponse
	(*Telemetry)(nil),        // 4: fleet.Telemetry
	(*Command)(nil),          // 5: fleet.Command
	nil,                      // 6: fleet.RegisterResponse.PointsEntry
}
var file_proto_fleet_proto_depIdxs = []int32{
	6, // 0: fleet.RegisterResponse.points:type_name -> fleet.RegisterResponse.PointsEntry
	0, // 1: fleet.Command.type:type_name -> fleet.CommandType
	1, // 2: fleet.RegisterResponse.PointsEntry.value:type_name -> fleet.Point
	2, // 3: fleet.FleetService.RegisterTruck:input_type -> fleet.RegisterRequest
	4, // 4: fleet.FleetService.SendTelemetry:input_type -> fleet.Telemetry
	3, // 5: fleet.FleetService.RegisterTruck:output_type -> fleet.RegisterResponse
	5, // 6: fleet.FleetService.SendTelemetry:output_type -> fleet.Command
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_fleet_proto_init() }
func file_proto_fleet_proto_init() {
	if File_proto_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fleet_proto_goTypes,
		DependencyIndexes: file_proto_fleet_proto_depIdxs,
		EnumInfos:         file_proto_fleet_proto_enumTypes,
		MessageInfos:      file_proto_fleet_proto_msgTypes,
	}.Build()
	File_proto_fleet_proto = out.File
	file_proto_fleet_proto_goTypes = nil
	file_proto_fleet_proto_depIdxs = nil
}
