syntax = "proto3";

package fleet;

option go_package = "github.com/MrBeetMaker/fleet-optimization/proto;fleetpb";

service FleetService {
    rpc RegisterTruck(RegisterRequest)
        returns (RegisterResponse);

    rpc SendTelemetry(Telemetry)
        returns (Command);
}

message Point {
  int32 x = 1;
  int32 y = 2;
}

message RegisterRequest {
    int32 truck_id = 1;
}

message RegisterResponse {
    bool accepted = 1;
    map<int32, Point> points = 2;
}

message Telemetry {
    int32  truck_id = 1;
    double x = 2;
    double y = 3;
    double battery = 4;
    int32  State = 5;
    int64  timestamp = 6;
}

enum CommandType {
    NONE = 0;
    STOP = 1;
    CONTINUE = 2;
    NEW_ROUTE = 3;
}

message Command {
    CommandType type = 1;
    repeated int32 route = 2;
}