# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fleet_pb2 as fleet__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTruck = channel.unary_unary(
                '/fleet.FleetService/RegisterTruck',
                request_serializer=fleet__pb2.RegisterRequest.SerializeToString,
                response_deserializer=fleet__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SendTelemetry = channel.unary_unary(
                '/fleet.FleetService/SendTelemetry',
                request_serializer=fleet__pb2.Telemetry.SerializeToString,
                response_deserializer=fleet__pb2.Command.FromString,
                _registered_method=True)
        self.RequestPickup = channel.unary_unary(
                '/fleet.FleetService/RequestPickup',
                request_serializer=fleet__pb2.PickUpRequest.SerializeToString,
                response_deserializer=fleet__pb2.PickUpResponse.FromString,
                _registered_method=True)
        self.RequestDelivery = channel.unary_unary(
                '/fleet.FleetService/RequestDelivery',
                request_serializer=fleet__pb2.DeliverRequest.SerializeToString,
                response_deserializer=fleet__pb2.DeliverResponse.FromString,
                _registered_method=True)


class FleetServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterTruck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPickup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTruck': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTruck,
                    request_deserializer=fleet__pb2.RegisterRequest.FromString,
                    response_serializer=fleet__pb2.RegisterResponse.SerializeToString,
            ),
            'SendTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTelemetry,
                    request_deserializer=fleet__pb2.Telemetry.FromString,
                    response_serializer=fleet__pb2.Command.SerializeToString,
            ),
            'RequestPickup': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPickup,
                    request_deserializer=fleet__pb2.PickUpRequest.FromString,
                    response_serializer=fleet__pb2.PickUpResponse.SerializeToString,
            ),
            'RequestDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDelivery,
                    request_deserializer=fleet__pb2.DeliverRequest.FromString,
                    response_serializer=fleet__pb2.DeliverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.FleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTruck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.FleetService/RegisterTruck',
            fleet__pb2.RegisterRequest.SerializeToString,
            fleet__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.FleetService/SendTelemetry',
            fleet__pb2.Telemetry.SerializeToString,
            fleet__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPickup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.FleetService/RequestPickup',
            fleet__pb2.PickUpRequest.SerializeToString,
            fleet__pb2.PickUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.FleetService/RequestDelivery',
            fleet__pb2.DeliverRequest.SerializeToString,
            fleet__pb2.DeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
