syntax = "proto3";

package fleet;

option go_package = "github.com/MrBeetMaker/fleet-optimization/proto;fleetpb";

service FleetService {
    rpc RegisterTruck(RegisterRequest)
        returns (RegisterResponse);

    rpc SendTelemetry(Telemetry)
        returns (Command);

    rpc RequestPickup(PickUpRequest)
        returns (PickUpResponse);

    rpc RequestDelivery(DeliverRequest)
        returns (DeliverResponse);

}

message Point {
  float x = 1;
  float y = 2;
}

message RegisterRequest {
    int32 truckId = 1;
}

message RegisterResponse {
    bool accepted = 1;
    map<int32, Point> points = 2;
}

message PickUpResponse {
    bool accepted = 1;
}

message PickUpRequest {
    int32 truckId = 1;
    int64 orderId = 2;
    int32 nodeId = 3;
}

message DeliverResponse {
    bool accepted = 1;
}

message DeliverRequest {
    int32 truckId = 1;
    int64 orderId = 2;
    int32 nodeId = 3;
}

message Order {
    int64 id = 1;
    float weight = 2;
    int32 size = 3;
    int32 pickUp = 4;       // Node id
    int32 dropOff = 5;      // Node id
    bool pickedUp = 6;
    bool delivered = 7;
    int32 truckId = 8;    // Truck assigned to order
}

enum TruckState {
  IDLE = 0;
  DRIVING = 1;
  CHARGING = 2;
  WAITING = 3;
  DELIVERING = 4;
}

message Telemetry {
  int32 truck_id = 1;
  double x = 2;
  double y = 3;
  double battery = 4;
  TruckState state = 5;
  int64 timestamp = 6;
  int32 dest = 7;
  Route route = 8;
  int32 current = 9; 
}

enum CommandType {
    NONE = 0;
    STOP = 1;
    CONTINUE = 2;
    NEW_ROUTE = 3;
}

message Route {
    repeated int32 nodes = 1;
}

message Command {
    CommandType type = 1;
    Route route = 2;
    repeated Order orders = 3;
}
