// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: optim.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Points        map[int32]*Point       `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NrOfTrucks    int32                  `protobuf:"varint,3,opt,name=nrOfTrucks,proto3" json:"nrOfTrucks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_optim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_optim_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRouteRequest) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *CreateRouteRequest) GetPoints() map[int32]*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *CreateRouteRequest) GetNrOfTrucks() int32 {
	if x != nil {
		return x.NrOfTrucks
	}
	return 0
}

type OrderIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIds) Reset() {
	*x = OrderIds{}
	mi := &file_optim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIds) ProtoMessage() {}

func (x *OrderIds) ProtoReflect() protoreflect.Message {
	mi := &file_optim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIds.ProtoReflect.Descriptor instead.
func (*OrderIds) Descriptor() ([]byte, []int) {
	return file_optim_proto_rawDescGZIP(), []int{1}
}

func (x *OrderIds) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CreateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        map[int32]*Route       `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrderIds      map[int32]*OrderIds    `protobuf:"bytes,2,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // RouteId -> list of order id's
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	mi := &file_optim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_optim_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRouteResponse) GetRoutes() map[int32]*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *CreateRouteResponse) GetOrderIds() map[int32]*OrderIds {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

var File_optim_proto protoreflect.FileDescriptor

const file_optim_proto_rawDesc = "" +
	"\n" +
	"\voptim.proto\x12\x05fleet\x1a\vfleet.proto\"\xe2\x01\n" +
	"\x12CreateRouteRequest\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.fleet.OrderR\x06orders\x12=\n" +
	"\x06points\x18\x02 \x03(\v2%.fleet.CreateRouteRequest.PointsEntryR\x06points\x12\x1e\n" +
	"\n" +
	"nrOfTrucks\x18\x03 \x01(\x05R\n" +
	"nrOfTrucks\x1aG\n" +
	"\vPointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.fleet.PointR\x05value:\x028\x01\"\x1c\n" +
	"\bOrderIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\xb3\x02\n" +
	"\x13CreateRouteResponse\x12>\n" +
	"\x06routes\x18\x01 \x03(\v2&.fleet.CreateRouteResponse.RoutesEntryR\x06routes\x12E\n" +
	"\torder_ids\x18\x02 \x03(\v2(.fleet.CreateRouteResponse.OrderIdsEntryR\borderIds\x1aG\n" +
	"\vRoutesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.fleet.RouteR\x05value:\x028\x01\x1aL\n" +
	"\rOrderIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.fleet.OrderIdsR\x05value:\x028\x012X\n" +
	"\x10OptimizerService\x12D\n" +
	"\vCreateRoute\x12\x19.fleet.CreateRouteRequest\x1a\x1a.fleet.CreateRouteResponseB9Z7github.com/MrBeetMaker/fleet-optimization/proto;fleetpbb\x06proto3"

var (
	file_optim_proto_rawDescOnce sync.Once
	file_optim_proto_rawDescData []byte
)

func file_optim_proto_rawDescGZIP() []byte {
	file_optim_proto_rawDescOnce.Do(func() {
		file_optim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optim_proto_rawDesc), len(file_optim_proto_rawDesc)))
	})
	return file_optim_proto_rawDescData
}

var file_optim_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_optim_proto_goTypes = []any{
	(*CreateRouteRequest)(nil),  // 0: fleet.CreateRouteRequest
	(*OrderIds)(nil),            // 1: fleet.OrderIds
	(*CreateRouteResponse)(nil), // 2: fleet.CreateRouteResponse
	nil,                         // 3: fleet.CreateRouteRequest.PointsEntry
	nil,                         // 4: fleet.CreateRouteResponse.RoutesEntry
	nil,                         // 5: fleet.CreateRouteResponse.OrderIdsEntry
	(*Order)(nil),               // 6: fleet.Order
	(*Point)(nil),               // 7: fleet.Point
	(*Route)(nil),               // 8: fleet.Route
}
var file_optim_proto_depIdxs = []int32{
	6, // 0: fleet.CreateRouteRequest.orders:type_name -> fleet.Order
	3, // 1: fleet.CreateRouteRequest.points:type_name -> fleet.CreateRouteRequest.PointsEntry
	4, // 2: fleet.CreateRouteResponse.routes:type_name -> fleet.CreateRouteResponse.RoutesEntry
	5, // 3: fleet.CreateRouteResponse.order_ids:type_name -> fleet.CreateRouteResponse.OrderIdsEntry
	7, // 4: fleet.CreateRouteRequest.PointsEntry.value:type_name -> fleet.Point
	8, // 5: fleet.CreateRouteResponse.RoutesEntry.value:type_name -> fleet.Route
	1, // 6: fleet.CreateRouteResponse.OrderIdsEntry.value:type_name -> fleet.OrderIds
	0, // 7: fleet.OptimizerService.CreateRoute:input_type -> fleet.CreateRouteRequest
	2, // 8: fleet.OptimizerService.CreateRoute:output_type -> fleet.CreateRouteResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_optim_proto_init() }
func file_optim_proto_init() {
	if File_optim_proto != nil {
		return
	}
	file_fleet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optim_proto_rawDesc), len(file_optim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optim_proto_goTypes,
		DependencyIndexes: file_optim_proto_depIdxs,
		MessageInfos:      file_optim_proto_msgTypes,
	}.Build()
	File_optim_proto = out.File
	file_optim_proto_goTypes = nil
	file_optim_proto_depIdxs = nil
}
