// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: optim.proto

package fleetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizerService_CreateRoute_FullMethodName = "/fleet.OptimizerService/CreateRoute"
)

// OptimizerServiceClient is the client API for OptimizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizerServiceClient interface {
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error)
}

type optimizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerServiceClient(cc grpc.ClientConnInterface) OptimizerServiceClient {
	return &optimizerServiceClient{cc}
}

func (c *optimizerServiceClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteResponse)
	err := c.cc.Invoke(ctx, OptimizerService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerServiceServer is the server API for OptimizerService service.
// All implementations must embed UnimplementedOptimizerServiceServer
// for forward compatibility.
type OptimizerServiceServer interface {
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error)
	mustEmbedUnimplementedOptimizerServiceServer()
}

// UnimplementedOptimizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerServiceServer struct{}

func (UnimplementedOptimizerServiceServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedOptimizerServiceServer) mustEmbedUnimplementedOptimizerServiceServer() {}
func (UnimplementedOptimizerServiceServer) testEmbeddedByValue()                          {}

// UnsafeOptimizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerServiceServer will
// result in compilation errors.
type UnsafeOptimizerServiceServer interface {
	mustEmbedUnimplementedOptimizerServiceServer()
}

func RegisterOptimizerServiceServer(s grpc.ServiceRegistrar, srv OptimizerServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizerService_ServiceDesc, srv)
}

func _OptimizerService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizerService_ServiceDesc is the grpc.ServiceDesc for OptimizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.OptimizerService",
	HandlerType: (*OptimizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _OptimizerService_CreateRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optim.proto",
}
