# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import optim_pb2 as optim__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in optim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptimizerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeOptimizer = channel.unary_unary(
                '/fleet.OptimizerService/InitializeOptimizer',
                request_serializer=optim__pb2.InitRequest.SerializeToString,
                response_deserializer=optim__pb2.InitResponse.FromString,
                _registered_method=True)
        self.CreateRoute = channel.unary_unary(
                '/fleet.OptimizerService/CreateRoute',
                request_serializer=optim__pb2.CreateRouteRequest.SerializeToString,
                response_deserializer=optim__pb2.CreateRouteResponse.FromString,
                _registered_method=True)


class OptimizerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeOptimizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeOptimizer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeOptimizer,
                    request_deserializer=optim__pb2.InitRequest.FromString,
                    response_serializer=optim__pb2.InitResponse.SerializeToString,
            ),
            'CreateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoute,
                    request_deserializer=optim__pb2.CreateRouteRequest.FromString,
                    response_serializer=optim__pb2.CreateRouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.OptimizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.OptimizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OptimizerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeOptimizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.OptimizerService/InitializeOptimizer',
            optim__pb2.InitRequest.SerializeToString,
            optim__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.OptimizerService/CreateRoute',
            optim__pb2.CreateRouteRequest.SerializeToString,
            optim__pb2.CreateRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
