# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optim.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'optim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fleet_pb2 as fleet__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0boptim.proto\x12\x05\x66leet\x1a\x0b\x66leet.proto\"z\n\x0bInitRequest\x12.\n\x06points\x18\x01 \x03(\x0b\x32\x1e.fleet.InitRequest.PointsEntry\x1a;\n\x0bPointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.fleet.Point:\x02\x38\x01\"\x1f\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xba\x01\n\x12\x43reateRouteRequest\x12\x1c\n\x06orders\x18\x01 \x03(\x0b\x32\x0c.fleet.Order\x12\x35\n\x06points\x18\x02 \x03(\x0b\x32%.fleet.CreateRouteRequest.PointsEntry\x12\x12\n\nnrOfTrucks\x18\x03 \x01(\x05\x1a;\n\x0bPointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.fleet.Point:\x02\x38\x01\"\x17\n\x08OrderIds\x12\x0b\n\x03ids\x18\x01 \x03(\x03\"\x89\x02\n\x13\x43reateRouteResponse\x12\x36\n\x06routes\x18\x01 \x03(\x0b\x32&.fleet.CreateRouteResponse.RoutesEntry\x12;\n\torder_ids\x18\x02 \x03(\x0b\x32(.fleet.CreateRouteResponse.OrderIdsEntry\x1a;\n\x0bRoutesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.fleet.Route:\x02\x38\x01\x1a@\n\rOrderIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.fleet.OrderIds:\x02\x38\x01\x32\x98\x01\n\x10OptimizerService\x12>\n\x13InitializeOptimizer\x12\x12.fleet.InitRequest\x1a\x13.fleet.InitResponse\x12\x44\n\x0b\x43reateRoute\x12\x19.fleet.CreateRouteRequest\x1a\x1a.fleet.CreateRouteResponseB9Z7github.com/MrBeetMaker/fleet-optimization/proto;fleetpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/MrBeetMaker/fleet-optimization/proto;fleetpb'
  _globals['_INITREQUEST_POINTSENTRY']._loaded_options = None
  _globals['_INITREQUEST_POINTSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEROUTEREQUEST_POINTSENTRY']._loaded_options = None
  _globals['_CREATEROUTEREQUEST_POINTSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEROUTERESPONSE_ROUTESENTRY']._loaded_options = None
  _globals['_CREATEROUTERESPONSE_ROUTESENTRY']._serialized_options = b'8\001'
  _globals['_CREATEROUTERESPONSE_ORDERIDSENTRY']._loaded_options = None
  _globals['_CREATEROUTERESPONSE_ORDERIDSENTRY']._serialized_options = b'8\001'
  _globals['_INITREQUEST']._serialized_start=35
  _globals['_INITREQUEST']._serialized_end=157
  _globals['_INITREQUEST_POINTSENTRY']._serialized_start=98
  _globals['_INITREQUEST_POINTSENTRY']._serialized_end=157
  _globals['_INITRESPONSE']._serialized_start=159
  _globals['_INITRESPONSE']._serialized_end=190
  _globals['_CREATEROUTEREQUEST']._serialized_start=193
  _globals['_CREATEROUTEREQUEST']._serialized_end=379
  _globals['_CREATEROUTEREQUEST_POINTSENTRY']._serialized_start=98
  _globals['_CREATEROUTEREQUEST_POINTSENTRY']._serialized_end=157
  _globals['_ORDERIDS']._serialized_start=381
  _globals['_ORDERIDS']._serialized_end=404
  _globals['_CREATEROUTERESPONSE']._serialized_start=407
  _globals['_CREATEROUTERESPONSE']._serialized_end=672
  _globals['_CREATEROUTERESPONSE_ROUTESENTRY']._serialized_start=547
  _globals['_CREATEROUTERESPONSE_ROUTESENTRY']._serialized_end=606
  _globals['_CREATEROUTERESPONSE_ORDERIDSENTRY']._serialized_start=608
  _globals['_CREATEROUTERESPONSE_ORDERIDSENTRY']._serialized_end=672
  _globals['_OPTIMIZERSERVICE']._serialized_start=675
  _globals['_OPTIMIZERSERVICE']._serialized_end=827
# @@protoc_insertion_point(module_scope)
